In [1]:
import pandas as pd 
import numpy as np

symptoms_diagnosis

In [2]:
df = pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\Cleaned_Symptoms.json")

In [3]:
df

,diagnosis,text
0,personality disorder,"Patient reported these symptoms: depression ,h..."
1,attention deficit hyperactivity disorder (adhd),"Patient reported these symptoms: depression ,d..."
2,muscle spasm,Patient reported these symptoms: abnormal invo...
3,diverticulitis,Patient reported these symptoms: sharp abdomin...
4,polycystic ovarian syndrome (pcos),"Patient reported these symptoms: hot flashes ,..."
...,...,...
469190,acute pancreatitis,"Patient reported these symptoms: vomiting ,nau..."
469191,atrial flutter,Patient reported these symptoms: shortness of ...
469192,otitis externa (swimmer's ear),"Patient reported these symptoms: sore throat ,..."
469193,croup,"Patient reported these symptoms: sore throat ,..."
469194,oral thrush (yeast infection),"Patient reported these symptoms: sore throat ,..."

medquad_cleaned

In [3]:
df= pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\Cleaned_medquad.json")

In [4]:
df

,Question,Answer
0,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."
...,...,...
16402,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...
16403,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...
16404,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...
16405,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...
16406,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ..."

Medical Meadow

In [5]:
df = pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\medical_meadow_dataset.json")

In [6]:
df

,input,output,instruction
0,Can you provide an overview of the lung's squa...,Squamous cell carcinoma of the lung may be cla...,Answer this question truthfully
1,"What does ""Clear: cell"" mean?",Clear cell tumors are part of the surface epit...,Answer this question truthfully
2,Can you provide me with information regarding ...,Two Japanese scientists commenced research int...,Answer this question truthfully
3,What are the historical background and symptom...,Symptoms of vulvovaginitis caused by Candida s...,Answer this question truthfully
4,"What does the ""Hypotension: Resident Survival ...",Hypotension is the term for low blood pressure...,Answer this question truthfully
...,...,...,...
9995,What are some biochemistry topics that can be ...,Water -,Answer this question truthfully
9996,What information is available on esophageal st...,Esophageal stricture is a narrowing of the eso...,Answer this question truthfully
9997,What is the main way to prevent basal cell car...,The development of basal cell carcinoma can be...,Answer this question truthfully
9998,Could you provide me with the text you want me...,No medical treatment is currently known or pra...,Answer this question truthfully
9999,What is the medical treatment for De Quervain'...,The mainstay of therapy for de Quervain's thyr...,Answer this question truthfully

chatdoctor

In [7]:
df = pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\chatdocter_Cleaned_data.json")

In [8]:
df

,instruction,input,output
0,"If you are a doctor, please answer the medical...",I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most..."
1,"If you are a doctor, please answer the medical...",My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....
2,"If you are a doctor, please answer the medical...","Hello, My husband is taking Oxycodone due to a...","Hello, and I hope I can help you today.First, ..."
3,"If you are a doctor, please answer the medical...",lump under left nipple and stomach pain (male)...,HI. You have two different problems. The lump ...
4,"If you are a doctor, please answer the medical...",I have a 5 month old baby who is very congeste...,Thank you for using Chat Doctor. I would sugge...
...,...,...,...
112160,"If you are a doctor, please answer the medical...",im 25 years old ..i started using mtp kit on 5...,"Hello, Thanks for letting us know your health ..."
112161,"If you are a doctor, please answer the medical...",My 5 year old son has been coughing for a mont...,As you have mentioned in your history that you...
112162,"If you are a doctor, please answer the medical...",My toes on right foot more than left are numb ...,Hi. The numbness and blue discoloration could ...
112163,"If you are a doctor, please answer the medical...","I was diagnosis with pleurisy last Tuesday, an...",Thanks for your question on Chat Doctor. Treat...
112164,"If you are a doctor, please answer the medical...","Within the past few hours, my husband has deve...","Hello, Thank you for posting on Chat Doctor. T..."

In [9]:
import json
import os 
folder = "symptoms_diagnosis_dataset"
# Load all datasets
with open("Cleaned_medquad.json", "r", encoding="utf-8") as f:
    medquad = json.load(f)

with open("chatdocter_Cleaned_data.json", "r", encoding="utf-8") as f:
    chatdoctor = json.load(f)

with open("medical_meadow_dataset.json", "r", encoding="utf-8") as f:
    medical_meadow = json.load(f)

with open("Cleaned_Symptoms.json", "r", encoding="utf-8") as f:
    symptoms = json.load(f)

merged_data = []

# 1. MedQuad
for row in medquad:
    merged_data.append({
        "source": "MedQuad",
        "input": row.get("Question", ""),
        "output": row.get("Answer", "")
    })

# 2. Chat Doctor
for row in chatdoctor:
    merged_data.append({
        "source": "ChatDoctor",
        "input": row.get("input", ""),
        "output": row.get("output", "")
    })

# 3. Medical Meadow
for row in medical_meadow:
    text_input = row.get("instruction", "") + " " + row.get("input", "")
    
    merged_data.append({
        "source": "MedicalMeadow",
        "input": text_input.strip(),
        "output": row.get("output", "")
    })

# 4. Symptoms to Diagnosis
for row in symptoms:
    merged_data.append({
        "source": "SymptomsDiagnosis",
        "input": row.get("diagnosis", ""),
        "output": row.get("text", "")
    })

# Save merged dataset
with open("merged_medical_dataset.json", "w", encoding="utf-8") as f:
    json.dump(merged_data, f, indent=4, ensure_ascii=False)

print("Merged successfully")
print("Total rows:", len(merged_data))

Merged successfully
Total rows: 607767

In [10]:
unique_data = []
seen = set()

for row in merged_data:
    pair = (row["input"], row["output"])
    if pair not in seen:
        seen.add(pair)
        unique_data.append(row)

print("After duplicate removal:", len(unique_data))

After duplicate removal: 502387

In [11]:
with open("clean_merged_dataset.json", "w", encoding="utf-8") as f:
    json.dump(unique_data, f, indent=4)

In [12]:
import os
print(os.getcwd())

d:\Santosh D\Study\College\Projects\SHIP

In [13]:
import os
print(os.listdir())

['all_slake_images', 'chatdocter_Cleaned_data.json', 'ChatDoctor_Cleaned.ipynb', 'Chest X .ipynb', 'chest_xray_1000_qa.json', 'chest_xray_dataset_json', 'chest_xray_images', 'chest_xray_qa_1000.json', 'Cleaned_Chatdocter_dataset.csv', 'Cleaned_chatdoctor_dataset', 'Cleaned_medquad.json', 'Cleaned_medquad_dataset.csv', 'Cleaned_Symptoms.json', 'clean_merged_dataset.json', 'final_master_qa_dataset.csv', 'final_slake_images', 'Harmonization.ipynb', 'imageCheck.py', 'images_metadata.json', 'image_dataset.json', 'main.py', 'master_qa_dataset.csv', 'Medical Meadow_Cleaned.ipynb', 'Medical Prescription dataset.ipynb', 'medical_meadow_dataset', 'medical_meadow_dataset.json', 'medical_prescription_dataset', 'MedQuad_Cleaned (1).ipynb', 'medquad_cleaned.csv', 'merged_medical_dataset.json', 'prescription_1000.csv', 'prescription_1000.json', 'ROCO - Radiology Object in Context.ipynb', 'roco_1000_jpg_images', 'roco_train_images', 'sample_image.jpg', 'SLAKEDATA_IMAGES.ipynb', 'slake_dataset.csv', 'slake_images', 'Symptoms_Cleaned.ipynb', 'symptoms_diagnosis_dataset', 'textCheck.py', 'Together_all_dataset.ipynb', 'unique_vqa_images', 'Untitled12.ipynb', 'VQA-RAD.ipynb', 'VQA-RAD_IMAGES.ipynb', 'vqa_rad.csv', 'vqa_rad_fixed.csv', 'vqa_rad_images', 'vqa_rad_jpg_images']

In [14]:
df = pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\clean_merged_dataset.json")

In [15]:
df

,source,input,output
0,MedQuad,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,MedQuad,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,MedQuad,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,MedQuad,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,MedQuad,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."
...,...,...,...
502382,SymptomsDiagnosis,tooth abscess,Patient reported these symptoms: skin swelling...
502383,SymptomsDiagnosis,tooth disorder,"Patient reported these symptoms: toothache ,fa..."
502384,SymptomsDiagnosis,acute pancreatitis,"Patient reported these symptoms: vomiting ,nau..."
502385,SymptomsDiagnosis,otitis externa (swimmer's ear),"Patient reported these symptoms: sore throat ,..."
502386,SymptomsDiagnosis,croup,"Patient reported these symptoms: sore throat ,..."

In [16]:
print(df.columns)

Index(['source', 'input', 'output'], dtype='object')

In [17]:
import pandas as pd

df = pd.read_json("merged_medical_dataset.json")

symptom_rows = df[df["source"] == "SymptomsDiagnosis"]

print(symptom_rows.head())

                   source                                            input  \
138572  SymptomsDiagnosis                             personality disorder
138573  SymptomsDiagnosis  attention deficit hyperactivity disorder (adhd)
138574  SymptomsDiagnosis                                     muscle spasm
138575  SymptomsDiagnosis                                   diverticulitis
138576  SymptomsDiagnosis               polycystic ovarian syndrome (pcos)

                                                   output
138572  Patient reported these symptoms: depression ,h...
138573  Patient reported these symptoms: depression ,d...
138574  Patient reported these symptoms: abnormal invo...
138575  Patient reported these symptoms: sharp abdomin...
138576  Patient reported these symptoms: hot flashes ,...